apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: deployment
spec:
   replicas: 2
   template:
     metadata:
       labels:
         app: helloworld
     spec:
        containers:
        - name: deployment-demo
          image: wardviaene/k8s-demo
          ports:
          - name: nodejs-port
            containerPort: 3000
